mode: rule
log-level: info
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  respect-rules: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - tls://dns.google
  proxy-server-nameserver:
    - tls://dot.pub
    - tls://dns.alidns.com
  direct-nameserver:
    - tls://dot.pub
    - tls://dns.alidns.com
  nameserver-policy:
    "*.makima.online":
      - 119.29.29.29
      - 223.5.5.4
  fake-ip-filter:
    - "*"
    - *.lan
    - time.*.com
    - ntp.*.com
