mode: rule
log-level: info
dns:
  enable: true
  ipv6: false
#   启动服务器，用于解析提供的 nameserver，只能用 IP
#   default-nameserver: 
#     - 223.5.5.5
#     - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
     - 119.29.29.29
     - 114.114.114.114
  fallback:
    - "https://1.1.1.1/dns-query"
    - "https://dns.cloudflare.com/dns-query"
    - "https://dns.alidns.com/dns-query"
